import { ArrowRight, CheckCircle2, ClipboardCheck, FileCheck2, Plus, ScanSearch, ShieldCheck, Waypoints } from 'lucide-react';
import { useState } from 'react';
import { getGetSourceStatusesQueryKey, getGetVerificationSummaryQueryKey, getListVerificationRunsQueryKey, useGetSourceStatuses, useGetVerificationSummary, useListVerificationRuns } from '@workspace/api-client-react';
import { Link } from 'wouter';
import { PageIntro, LoadingRows, QueryState, RunRow, SourceCard, formatDate } from '@/components/shared';
import { LaunchVerification } from '@/components/launch-verification';

export default function Overview() {
  const summary = useGetVerificationSummary({ query: { queryKey: getGetVerificationSummaryQueryKey() } });
  const runs = useListVerificationRuns({ limit: 4 }, { query: { queryKey: getListVerificationRunsQueryKey({ limit: 4 }) } });
  const sources = useGetSourceStatuses({ query: { queryKey: getGetSourceStatusesQueryKey() } });
  const [launchOpen, setLaunchOpen] = useState(false);

  return <div className="reveal-up">
    <PageIntro eyebrow="Verification command center" title="Know when the number changed." description="Reconcile public-health indicators across trusted sources, then preserve the evidence trail as a verifiable record." action={<button onClick={() => setLaunchOpen(true)} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-[13px] font-bold text-primary-foreground shadow-sm transition-transform hover:-translate-y-0.5" data-testid="button-launch-verification"><Plus size={16} /> Launch verification</button>} />

    {summary.isLoading ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" data-testid="summary-loading">{Array.from({ length: 4 }).map((_, i) => <div key={i} className="h-[123px] animate-pulse rounded-xl bg-muted" />)}</div> : summary.isError ? <QueryState kind="error" onRetry={() => summary.refetch()} /> : summary.data ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" data-testid="summary-grid">
      {[{ label: 'Verification runs', value: summary.data.totalRuns.toLocaleString(), note: 'All time comparisons', icon: ClipboardCheck }, { label: 'Anchored to chain', value: summary.data.anchoredRuns.toLocaleString(), note: 'Polygon Amoy proofs', icon: ShieldCheck }, { label: 'Source agreement', value: `${summary.data.sourceAgreement.toFixed(1)}%`, note: 'Across reconciled records', icon: CheckCircle2 }, { label: 'Records compared', value: summary.data.recordsCompared.toLocaleString(), note: 'DHIS2 + WHO coverage', icon: Waypoints }].map(({ label, value, note, icon: Icon }, i) => <div key={label} className={`relative overflow-hidden rounded-xl border border-border/80 bg-card p-5 shadow-xs ${i === 2 ? 'border-primary/25' : ''}`} data-testid={`metric-${label.toLowerCase().replaceAll(' ', '-')}`}><div className="absolute right-4 top-4 text-primary/55"><Icon size={18} /></div><div className="font-mono text-[10px] uppercase tracking-[.12em] text-muted-foreground">{label}</div><div className="mt-4 font-serif text-3xl font-extrabold tracking-[-.05em]">{value}</div><div className="mt-1 text-[11px] text-muted-foreground">{note}</div></div>)}</div> : <QueryState kind="empty" message="Summary data will appear after the first verified comparison." />}

    <div className="mt-8 grid gap-6 xl:grid-cols-[1.4fr_.85fr]">
      <section className="rounded-xl border border-border/80 bg-card p-5 shadow-xs sm:p-6" data-testid="section-recent-runs"><div className="mb-5 flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.13em] text-primary"><FileCheck2 size={13} /> Recent evidence</div><h2 className="mt-2 font-serif text-xl font-extrabold tracking-[-.03em]">Latest verification runs</h2></div><Link href="/runs" className="flex items-center gap-1 text-xs font-bold text-primary hover:underline" data-testid="link-view-all-runs">View all <ArrowRight size={14} /></Link></div>{runs.isLoading ? <LoadingRows count={3} /> : runs.isError ? <QueryState kind="error" onRetry={() => runs.refetch()} /> : runs.data?.length ? <div className="space-y-2.5">{runs.data.map(run => <RunRow key={run.id} run={run} />)}</div> : <QueryState kind="empty" />}</section>
      <section className="rounded-xl border border-border/80 bg-card p-5 shadow-xs sm:p-6" data-testid="section-source-health"><div className="mb-5 flex items-start justify-between"><div><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.13em] text-primary"><ScanSearch size={13} /> Source health</div><h2 className="mt-2 font-serif text-xl font-extrabold tracking-[-.03em]">Can we query the evidence?</h2></div><Link href="/sources" className="text-xs font-bold text-primary hover:underline" data-testid="link-manage-sources">Manage</Link></div>{sources.isLoading ? <LoadingRows count={3} /> : sources.isError ? <QueryState kind="error" onRetry={() => sources.refetch()} /> : sources.data?.length ? <div className="space-y-2.5">{sources.data.map(source => <SourceCard key={source.id} source={source} compact />)}</div> : <QueryState kind="empty" message="No source status has been configured yet." />}</section>
    </div>

    <div className="mt-6 grid gap-5 rounded-xl border border-[#c8a16b]/30 bg-[#d6a153]/[.08] p-5 sm:grid-cols-[1fr_auto] sm:items-center sm:p-6" data-testid="callout-anchor"><div><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.11em] text-[#986824]"><ShieldCheck size={15} /> Why anchoring matters</div><p className="mt-2 max-w-2xl text-[13px] leading-6 text-[#765b31]">A content hash lets your institution prove that a report is the same report it reviewed. The source numbers stay where they are; the integrity signal stays independently checkable.</p></div><div className="border-l border-[#c8a16b]/35 pl-5 text-right"><div className="font-mono text-[10px] uppercase tracking-[.1em] text-[#986824]">Last verified</div><div className="mt-1 font-serif text-lg font-bold text-[#765b31]">{formatDate(summary.data?.lastVerifiedAt, false)}</div></div></div>
    <LaunchVerification open={launchOpen} onOpenChange={setLaunchOpen} />
  </div>;
}