import { ArrowLeft, Blocks, CheckCircle2, Copy, ExternalLink, Fingerprint, FileText, Link2, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { useGetVerificationRun, getGetVerificationRunQueryKey } from '@workspace/api-client-react';
import { Link, useParams } from 'wouter';
import { PageIntro, LoadingRows, ProofMark, QueryState, SourceResultRow, StatusPill, formatDate, shortHash } from '@/components/shared';

export default function RunDetail() {
  const params = useParams<{ id: string }>();
  const id = Number(params.id);
  const query = useGetVerificationRun(id, { query: { queryKey: getGetVerificationRunQueryKey(id), enabled: Number.isFinite(id) } });
  const [copied, setCopied] = useState('');
  const copyValue = (label: string, value: string) => {
    navigator.clipboard?.writeText(value);
    setCopied(label);
    window.setTimeout(() => setCopied(''), 1600);
  };

  if (!Number.isFinite(id)) return <QueryState kind="error" message="This run address is not valid." />;
  if (query.isLoading) return <LoadingRows count={5} />;
  if (query.isError || !query.data) return <QueryState kind="error" onRetry={() => query.refetch()} message="This run could not be retrieved. No claim has been made about its evidence." />;
  const run = query.data;
  const anchored = run.status === 'anchored' && Boolean(run.txHash);

  return <div className="reveal-up">
    <Link href="/runs" className="mb-6 inline-flex items-center gap-2 text-xs font-bold text-muted-foreground hover:text-primary" data-testid="link-back-runs"><ArrowLeft size={14} /> Back to verification runs</Link>
    <PageIntro eyebrow={`Run ${String(run.id).padStart(5, '0')} / Evidence report`} title={run.indicator} description={`${run.geography} · ${run.period} · Created ${formatDate(run.createdAt)}`} action={<ProofMark anchored={anchored} />} />

    <div className="grid gap-5 xl:grid-cols-[1.35fr_.75fr]">
      <div className="space-y-5">
        <section className="rounded-xl border border-border/80 bg-card p-5 shadow-xs sm:p-6" data-testid="section-report-summary"><div className="mb-5 flex items-center justify-between gap-4"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.13em] text-primary"><FileText size={14} /> Reconciled report</div><StatusPill status={run.status} /></div><div className="rounded-lg border-l-2 border-primary bg-primary/[.05] px-4 py-3 text-sm leading-6 text-foreground">{run.report || 'No narrative report was returned for this run.'}</div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-lg bg-muted/60 p-3"><div className="font-mono text-[10px] uppercase tracking-[.08em] text-muted-foreground">Agreement</div><div className="mt-2 font-serif text-2xl font-extrabold">{run.agreement.toFixed(1)}%</div></div><div className="rounded-lg bg-muted/60 p-3"><div className="font-mono text-[10px] uppercase tracking-[.08em] text-muted-foreground">Records compared</div><div className="mt-2 font-serif text-2xl font-extrabold">{run.recordsCompared.toLocaleString()}</div></div><div className="col-span-2 rounded-lg bg-muted/60 p-3 sm:col-span-1"><div className="font-mono text-[10px] uppercase tracking-[.08em] text-muted-foreground">Observed</div><div className="mt-2 font-serif text-lg font-extrabold">{formatDate(run.createdAt, false)}</div></div></div></section>
        <section className="rounded-xl border border-border/80 bg-card p-5 shadow-xs sm:p-6" data-testid="section-source-comparison"><div className="mb-2 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.13em] text-primary"><CheckCircle2 size={14} /> Source comparison</div><h2 className="font-serif text-xl font-extrabold tracking-[-.03em]">What each source returned</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Values are shown exactly as received for this verification request. A match is not a statement of clinical truth; it is a statement of source agreement.</p><div className="mt-4">{run.sourceResults?.length ? run.sourceResults.map((result, index) => <SourceResultRow key={`${result.source}-${index}`} result={result} />) : <div className="py-8 text-center text-sm text-muted-foreground">No source records were returned.</div>}</div></section>
      </div>
      <div className="space-y-5">
        <section className="rounded-xl border border-border/80 bg-card p-5 shadow-xs" data-testid="section-hash-proof"><div className="mb-4 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.13em] text-[#986824]"><Fingerprint size={14} /> Integrity record</div><h2 className="font-serif text-xl font-extrabold tracking-[-.03em]">The proof layer</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">The report fingerprint below can be compared independently with the anchored transaction.</p><div className="mt-5 space-y-3"><div className="rounded-lg border border-border bg-muted/40 p-3"><div className="mb-2 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[.08em] text-muted-foreground">Content hash</span><button onClick={() => copyValue('hash', run.contentHash)} className="text-muted-foreground hover:text-primary" aria-label="Copy content hash" data-testid="button-copy-hash"><Copy size={14} /></button></div><div className="break-all font-mono text-[11px] leading-5 text-foreground">{shortHash(run.contentHash)}{copied === 'hash' && <span className="ml-2 text-primary">Copied</span>}</div></div><div className="rounded-lg border border-border bg-muted/40 p-3"><div className="mb-2 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[.08em] text-muted-foreground">Transaction hash</span>{run.txHash && <button onClick={() => copyValue('tx', run.txHash ?? '')} className="text-muted-foreground hover:text-primary" aria-label="Copy transaction hash" data-testid="button-copy-transaction"><Copy size={14} /></button>}</div><div className="break-all font-mono text-[11px] leading-5 text-foreground">{run.txHash ? shortHash(run.txHash) : 'Not recorded'}{copied === 'tx' && <span className="ml-2 text-primary">Copied</span>}</div></div></div>{run.explorerUrl && <a href={run.explorerUrl} target="_blank" rel="noreferrer" className="mt-4 flex items-center justify-center gap-2 rounded-lg border border-primary/25 bg-primary/5 py-2.5 text-xs font-bold text-primary hover:bg-primary/10" data-testid="link-view-transaction"><Blocks size={14} /> View on Polygon explorer <ExternalLink size={13} /></a>}</section>
        <section className="rounded-xl border border-border/80 bg-card p-5 shadow-xs" data-testid="section-traceability"><div className="mb-4 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.13em] text-primary"><Link2 size={14} /> Traceability</div><div className="space-y-0"><div className="flex gap-3"><div className="flex flex-col items-center"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-primary/10 text-primary"><CheckCircle2 size={15} /></div><div className="h-8 w-px bg-border" /></div><div className="pb-5"><div className="text-xs font-bold">Sources queried</div><div className="mt-1 text-[11px] text-muted-foreground">DHIS2 and WHO records collected</div></div></div><div className="flex gap-3"><div className="flex flex-col items-center"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-primary/10 text-primary"><ShieldCheck size={15} /></div><div className="h-8 w-px bg-border" /></div><div className="pb-5"><div className="text-xs font-bold">Evidence reconciled</div><div className="mt-1 text-[11px] text-muted-foreground">Values compared and report generated</div></div></div><div className="flex gap-3"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-[#d6a153]/20 text-[#986824]"><Blocks size={15} /></div><div><div className="text-xs font-bold">{anchored ? 'Hash anchored' : 'Hash not anchored'}</div><div className="mt-1 text-[11px] text-muted-foreground">{anchored ? 'Integrity proof recorded on Polygon Amoy' : 'This run has no chain proof'}</div></div></div></div></section>
      </div>
    </div>
  </div>;
}