import { Blocks, Check, Clipboard, Database, ExternalLink, RefreshCw, Server, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { useGetSourceStatuses, getGetSourceStatusesQueryKey } from '@workspace/api-client-react';
import { PageIntro, LoadingRows, QueryState, SourceCard } from '@/components/shared';

export default function Sources() {
  const sources = useGetSourceStatuses({ query: { queryKey: getGetSourceStatusesQueryKey() } });
  const [copied, setCopied] = useState(false);
  const copy = () => { navigator.clipboard?.writeText('Polygon Amoy · chain ID 80002'); setCopied(true); window.setTimeout(() => setCopied(false), 1600); };
  return <div className="reveal-up">
    <PageIntro eyebrow="Connections & provenance" title="Sources and chain" description="Understand which systems can be queried, when they were last checked, and where the integrity proof is written. Unavailable sources are never treated as verified." action={<button onClick={() => sources.refetch()} className="inline-flex items-center justify-center gap-2 rounded-lg border border-border bg-card px-3.5 py-2.5 text-xs font-bold shadow-xs hover:bg-muted" data-testid="button-refresh-sources"><RefreshCw size={14} className={sources.isFetching ? 'animate-spin' : ''} /> Refresh statuses</button>} />
    <section className="mb-7 rounded-xl border border-[#c8a16b]/30 bg-[#d6a153]/[.08] p-5 sm:p-6" data-testid="section-chain-setup"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#d6a153]/20 text-[#986824]"><Blocks size={19} /></div><div><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.1em] text-[#986824]">Integrity destination <span className="h-1.5 w-1.5 rounded-full bg-[#b97b24]" /></div><h2 className="mt-1.5 font-serif text-xl font-extrabold tracking-[-.03em] text-[#765b31]">Polygon Amoy testnet</h2><p className="mt-2 max-w-xl text-xs leading-5 text-[#765b31]/80">Every anchored run writes a content hash to the public test network. This is provenance infrastructure, not a claim about the clinical data itself.</p></div></div><div className="flex shrink-0 gap-2"><button onClick={copy} className="inline-flex items-center gap-1.5 rounded-lg border border-[#c8a16b]/35 bg-card/50 px-3 py-2 text-[11px] font-bold text-[#765b31] hover:bg-card" data-testid="button-copy-network">{copied ? <Check size={13} /> : <Clipboard size={13} />}{copied ? 'Copied' : 'Copy network'}</button><a href="https://amoy.polygonscan.com" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 rounded-lg border border-[#c8a16b]/35 bg-card/50 px-3 py-2 text-[11px] font-bold text-[#765b31] hover:bg-card" data-testid="link-open-network"><ExternalLink size={13} /> Explorer</a></div></div></section>
    <div className="mb-4 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.15em] text-primary"><Server size={13} /> Configured systems</div>
    {sources.isLoading ? <div className="grid gap-4 lg:grid-cols-3"><LoadingRows count={2} /><LoadingRows count={2} /><LoadingRows count={2} /></div> : sources.isError ? <QueryState kind="error" onRetry={() => sources.refetch()} /> : sources.data?.length ? <div className="grid gap-4 lg:grid-cols-3">{sources.data.map(source => <SourceCard key={source.id} source={source} />)}</div> : <QueryState kind="empty" message="Connect a DHIS2, WHO, or chain endpoint to begin recording source posture." />}
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-border/80 bg-card p-4 shadow-xs"><div className="mb-3 flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary"><Database size={16} /></div><div className="text-xs font-bold">Source identity</div><p className="mt-1.5 text-[11px] leading-5 text-muted-foreground">Every value retains its originating system and observation time.</p></div><div className="rounded-xl border border-border/80 bg-card p-4 shadow-xs"><div className="mb-3 flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary"><ShieldCheck size={16} /></div><div className="text-xs font-bold">No silent fallbacks</div><p className="mt-1.5 text-[11px] leading-5 text-muted-foreground">Unavailable or demo responses stay visibly labeled in the report.</p></div><div className="rounded-xl border border-border/80 bg-card p-4 shadow-xs"><div className="mb-3 flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary"><Blocks size={16} /></div><div className="text-xs font-bold">Public proof</div><p className="mt-1.5 text-[11px] leading-5 text-muted-foreground">Anchored hashes can be independently checked on the testnet explorer.</p></div></div>
  </div>;
}